"""Initial Migration

Revision ID: 1a73f06ff56a
Revises: 26018d0e3d5a
Create Date: 2020-10-26 23:08:12.662128

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a73f06ff56a'
down_revision = '26018d0e3d5a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pitches', sa.Column('pitcher', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pitches', 'pitcher')
    # ### end Alembic commands ###
