"""Initial Migration

Revision ID: 26018d0e3d5a
Revises: c247c91bd268
Create Date: 2020-10-26 20:55:46.790763

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26018d0e3d5a'
down_revision = 'c247c91bd268'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pitches', 'owner_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pitches', 'owner_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
