"""Initial Migration

Revision ID: 8293629fba65
Revises: d098c93d38fb
Create Date: 2020-10-25 16:45:53.119067

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8293629fba65'
down_revision = 'd098c93d38fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pitches', sa.Column('category_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pitches', 'category_id')
    # ### end Alembic commands ###
