"""Initial Migration

Revision ID: 874f5df20de1
Revises: 4e72adae593d
Create Date: 2020-10-24 17:10:26.005056

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '874f5df20de1'
down_revision = '4e72adae593d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('pass_secure', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_column('users', 'pass_secure')
    op.drop_column('users', 'email')
    # ### end Alembic commands ###
