"""Initial Migration

Revision ID: be2fb28fd3fb
Revises: 8293629fba65
Create Date: 2020-10-25 16:51:31.443096

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be2fb28fd3fb'
down_revision = '8293629fba65'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pitches', sa.Column('category', sa.String(), nullable=True))
    op.drop_column('pitches', 'category_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pitches', sa.Column('category_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('pitches', 'category')
    # ### end Alembic commands ###
